import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  // Stili della card
  card: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: 16,
    marginVertical: 4,
    marginHorizontal: 16,
    borderWidth: 1,
    borderColor: "#e1e5e9",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  completedCard: {
    backgroundColor: "#f8f8f8",
  },
  
  // Layout
  topRow: {
    flexDirection: "row",
    alignItems: "flex-start",
  },
  taskInfo: {
    flex: 1,
  },
  infoRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
  },
    // Testo
  title: {
    fontSize: 17,
    fontWeight: "400",
    color: "#000000",
    marginBottom: 8,
    fontFamily: "System",
    letterSpacing: -0.3,
  },
  completedText: {
    textDecorationLine: "line-through",
    color: "#999999",
  },
  description: {
    fontSize: 15,
    color: "#666666",
    lineHeight: 22,
    paddingLeft: 34, // Align with title text
    fontFamily: "System",
    fontWeight: "300",
  },
  
  descriptionContainer: {
    marginTop: 10,
    paddingBottom: 5,
    overflow: 'hidden',
  },
    // Checkbox
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 1.5,
    borderColor: "#e1e5e9",
    marginRight: 12,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 2,
    backgroundColor: "#ffffff",
  },
  checkedBox: {
    backgroundColor: "#000000",
    borderColor: "#000000",
  },
  optimisticBox: {
    backgroundColor: "#ff9800",
    borderColor: "#ff9800",
  },
    // Data e giorni rimanenti
  dateContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  dateText: {
    fontSize: 13,
    color: "#666666",
    marginLeft: 4,
    fontWeight: "400",
    fontFamily: "System",
  },
  daysRemainingContainer: {
    marginLeft: 'auto',
    marginRight: 8,
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  daysRemaining: {
    fontSize: 13,
    fontWeight: "500",
    textAlign: 'right',
    fontFamily: "System",
  },
  
  // Pulsanti e menu
  expandButton: {
    alignSelf: "center",
    marginTop: 4,
  },
  menuButton: {
    padding: 4,
  },
  menu: {
    borderRadius: 8,
    marginTop: 8,
  },
    // Stili del modal
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  menuContainer: {
    width: 220,
    backgroundColor: '#ffffff',
    borderRadius: 16,
    paddingVertical: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#e1e5e9',
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 20,
  },
  menuText: {
    fontSize: 17,
    marginLeft: 16,
    color: '#000000',
    fontFamily: "System",
    fontWeight: '400',
  },
  
  // Stili per il modal di modifica
  editModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },  editModalContainer: {
    width: '100%',
    height: '92%',
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    overflow: 'hidden',
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 8,
  },
  editModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 24,
    borderBottomWidth: 1,
    borderBottomColor: '#e1e5e9',
    backgroundColor: '#ffffff',
  },
  editModalTitle: {
    fontSize: 24,
    fontWeight: '300',
    color: '#000000',
    fontFamily: "System",
    letterSpacing: -0.5,
  },
  editModalContent: {
    padding: 24,
  },
  editModalFooter: {
    padding: 24,
    borderTopWidth: 1,
    borderTopColor: '#e1e5e9',
    alignItems: 'center',
  },
  inputLabel: {
    fontSize: 16,
    fontWeight: '400',
    marginBottom: 12,
    color: '#000000',
    fontFamily: "System",
  },  input: {
    borderWidth: 1.5,
    borderColor: '#e1e5e9',
    borderRadius: 16,
    padding: 16,
    marginBottom: 20,
    fontSize: 17,
    backgroundColor: '#ffffff',
    fontFamily: "System",
    fontWeight: '400',
    color: '#000000',
  },
  textArea: {
    height: 120,
  },
  datePickerButton: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#e1e5e9',
    borderRadius: 16,
    padding: 16,
    marginBottom: 20,
    backgroundColor: '#ffffff',
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  datePickerText: {
    fontSize: 17,
    color: '#000000',
    fontFamily: "System",
    fontWeight: '400',
  },priorityContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  priorityButton: {
    flex: 1,
    padding: 16,
    borderRadius: 16,
    marginHorizontal: 6,
    alignItems: 'center',
    borderWidth: 1.5,
    backgroundColor: '#ffffff',
  },
  priorityButtonLow: {
    borderColor: '#e1e5e9',
  },
  priorityButtonMedium: {
    borderColor: '#e1e5e9',
  },
  priorityButtonHigh: {
    borderColor: '#e1e5e9',
  },  priorityButtonActive: {
    borderWidth: 2,
    borderColor: '#000000',
    backgroundColor: '#000000',
  },
  priorityButtonText: {
    fontWeight: '400',
    fontSize: 16,
    color: '#666666',
    fontFamily: "System",
  },
  priorityButtonTextActive: {
    fontWeight: '500',
    color: '#ffffff',
  },
  saveButton: {
    backgroundColor: '#000000',
    paddingVertical: 16,
    paddingHorizontal: 32,
    borderRadius: 24,
    width: '100%',
    alignItems: 'center',
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
  },  saveButtonText: {
    color: '#ffffff',
    fontWeight: '400',
    fontSize: 17,
    fontFamily: "System",
  },
  dateTimeContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  dateButton: {
    flex: 3,
    marginRight: 8,
  },
  timeButton: {
    flex: 2,
  },
  statusContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  statusButtonPending: {
    borderColor: '#e1e5e9',
    backgroundColor: '#ffffff',
  },
  statusButtonInProgress: {
    borderColor: '#e1e5e9',
    backgroundColor: '#ffffff',
  },
  statusButtonCompleted: {
    borderColor: '#e1e5e9',
    backgroundColor: '#ffffff',
  },
  clearDateButton: {
    alignSelf: 'center',
    marginTop: -8,
    marginBottom: 16,
    paddingVertical: 8,
    paddingHorizontal: 16,
  },
  clearDateText: {
    color: '#FF5252',
    fontSize: 14,
    fontFamily: 'System',
    textDecorationLine: 'underline',
  },
  // Recurring task styles
  daysOfWeekContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  dayButton: {
    width: '13%',
    aspectRatio: 1,
    borderRadius: 20,
    marginVertical: 4,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: '#e1e5e9',
    backgroundColor: '#ffffff',
  },
  dayButtonActive: {
    borderWidth: 2,
    borderColor: '#000000',
    backgroundColor: '#000000',
  },
  dayButtonText: {
    fontSize: 13,
    color: '#666666',
    fontFamily: 'System',
    fontWeight: '400',
  },
  dayButtonTextActive: {
    fontWeight: '500',
    color: '#ffffff',
  },
  numberInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
    borderWidth: 1.5,
    borderColor: '#e1e5e9',
    borderRadius: 16,
    backgroundColor: '#ffffff',
    paddingVertical: 8,
  },
  numberButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
  },
  numberInputField: {
    flex: 1,
    textAlign: 'center',
    fontSize: 17,
    fontFamily: 'System',
    fontWeight: '400',
    color: '#000000',
    paddingHorizontal: 16,
  },
  // Duration styles
  durationContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  durationChip: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: '#e1e5e9',
    backgroundColor: '#ffffff',
  },
  durationChipActive: {
    borderColor: '#000000',
    backgroundColor: '#000000',
    borderWidth: 2,
  },
  durationChipText: {
    fontSize: 14,
    color: '#666666',
    fontFamily: 'System',
    fontWeight: '400',
  },
  durationChipTextActive: {
    color: '#ffffff',
    fontWeight: '500',
  },
  customDurationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
  },
  customDurationInput: {
    flex: 1,
    borderWidth: 1.5,
    borderColor: '#e1e5e9',
    borderRadius: 16,
    padding: 14,
    fontSize: 15,
    backgroundColor: '#ffffff',
    fontFamily: 'System',
    color: '#000000',
  },
  clearDurationButton: {
    marginLeft: 8,
    padding: 4,
  },
  // Duration display (for TaskHeader/BasicComponents)
  durationContainer2: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  durationText: {
    fontSize: 12,
    color: '#666666',
    marginLeft: 4,
    fontWeight: '400',
    fontFamily: 'System',
  },
});